apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: titanic-challenge
spec:
  selector:
    matchLabels:
      app: titanic-api
  jwtRules:
    - issuer: "http://titanic-api.titanic-challenge.svc.cluster.local:8000"
      jwksUri: "http://titanic-api.titanic-challenge.svc.cluster.local:8000/auth/.well-known/jwks.json"
      forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: docs-public-access
  namespace: titanic-challenge
spec:
  selector:
    matchLabels:
      app: titanic-api
  action: ALLOW
  rules:
    - to:
      - operation:
          paths: ["/docs", "/docs/*", "/openapi.json", "/auth/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: api-auth
  namespace: titanic-challenge
spec:
  selector:
    matchLabels:
      app: titanic-api
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
      to:
      - operation:
          methods: ["GET"]
          paths: ["/schema", "/statistics/*", "/passengers/*", "/analysis/*"]
