apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-api
  namespace: titanic-challenge
  labels:
    app: titanic-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: titanic-api
  template:
    metadata:
      labels:
        app: titanic-api
    spec:
      containers:
      - name: titanic-api
        image: {{ .Values.api.image }}
        {{- if .Values.api.development.enabled }}
        command: {{ .Values.api.development.command | toJson }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        env:
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key
              key: tls.key
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key
              key: tls.crt
        - name: DEMO_USERS_JSON
          valueFrom:
            secretKeyRef:
              name: auth-users
              key: users.json
        ports:
        - containerPort: 8000
        resources: {{ toYaml .Values.api.resources | nindent 10 }}
