apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: titanic-gateway
  namespace: titanic-challenge
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: titanic-credential
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: titanic-api
  namespace: titanic-challenge
spec:
  hosts:
  - "*"
  gateways:
  - titanic-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: titanic-api
        port:
          number: 8000
