apiVersion: v1
kind: Secret
metadata:
  name: auth-users
  namespace: titanic-challenge
type: Opaque
stringData:
  users.json: |
    {
      "analyst": {
        "password": "demo123",
        "role": "data-analyst"
      },
      "viewer": {
        "password": "demo123",
        "role": "viewer"
      }
    }
