apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: titanic-credential
  namespace: istio-system
spec:
  secretName: titanic-credential
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: titanic.local
  dnsNames:
    - titanic.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
