apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: istio-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: titanic-credential
  namespace: istio-system
spec:
  secretName: titanic-credential
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: titanic.local
  dnsNames:
    - titanic.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: titanic-challenge
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jwt-signing-key
  namespace: titanic-challenge
spec:
  secretName: jwt-signing-key
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: titanic-api.titanic-challenge.svc.cluster.local
  dnsNames:
    - titanic-api.titanic-challenge.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
